#!/bin/bash
sudo apt-get update
sudo apt-get install -y nfs-kernel-server
sudo mkdir /users/Hongmiao/share
sudo chmod 777 /users/Hongmiao/share/
echo '/users/Hongmiao/share 10.10.1.0/255.255.255.0(rw,sync,no_subtree_check)' > /etc/exports
sudo exportfs -r
sudo systemctl restart nfs-kernel-server
